name: devit
description: The Devit conference

permalink: /:categories/:title

disqus: devitconf

exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  ".*",
  "CONTRIBUTING.md",
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md",
  "_js"
]

analytics:
  google:
    tracker: 'UA-41787746-8'

future: true
show_drafts: true

markdown: kramdown

highlighter: pygments

encoding: utf-8
