# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: devit
description: The Devit conference

permalink: /:categories/:title

authors:
  thanpolas:
    name: Thanasis Polychronakis
    display_name: Thanasis
    gravatar: cbb9cafe03e785d80a9aa973c5e43c44
    email: thanpolas@gmail.com
    web: http://thanpol.as
    twitter: thanpolas
    github: thanpolas
  marga:
    name: Konstantinos Margaritis
    display_name: Konstantinos Margaritis
    gravatar: 15a64213080e0ee13d02f0eab0f8819b
    email: kostas@devitconf.org
    web: http://typeofundefined.io/
    twitter: _margaritis
    github: margaritis
  toubou91:
    name: Thodoris Bais
    display_name: Thodoris Bais
    gravatar: aa23ddc3794ffee7156c9ff1428d9baf
    email: thodoris.bais@gmail.com
    web: https://www.facebook.com/toubou.techblog
    twitter: ThodorisBais
    github: toubou91
  Amalia:
    name: Amalia Vradi
    display_name: Amalia
    twitter: alkistics
    github: amaliavr

disqus: devitconf

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts


# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

analytics:
  google:
    tracker: 'UA-41787746-8'

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

highlighter: pygments

encoding: utf-8
