name: devit
description: The DEVit conference

url: https://devitconf.org

exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  ".*",
  "CONTRIBUTING.md",
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md",
  "_js"
]

og:
  title: JUN 09-10, 2019 - DEVit the 360° Web Development Conference
  description: Find out the latest trends and techniques for Frontend, Backend, DevOps and Mobile! Meet all the cool people! We are 360° and proud of it!
  image: http://devitconf.org/assets/images/devit-og-general.jpg?1516005203

analytics:
  fb:
    tracker: '1071961509597865'
  google:
    tracker: 'UA-41787746-8'

encoding: utf-8

responsive_image:
  template: _includes/responsive-image.html

  sizes:
    - width: 800
    - width: 1000

  strip: true

  cache: false

url: "https://devitconf.org"
gems:
  - jekyll-sitemap
