##
## The purpose of this configuration is to allow us to put
## toggles on things that change regulary in order to be
## switching them faster in the future
##

defaults:
  title: JUN 10-11, 2018, Thessaloniki
  description: Find out the latest trends and techniques for Frontend, Backend, DevOps and Mobile! Meet all the cool people! We are 360Â° and proud of it!
  image: /assets/images/devit-og-general.jpg?1524042961

date: JUN 10-11, 2018
currentYear: "2018"

startDate: "2018-06-10"
endDate: "2018-06-11"

titlePostfix: " - DEVit Conference"

# Info about the venue
venue: blah blah

# Current mode. Site will be modified based on this
currentMode: "dday|nextday|nextblind|nextfull"

isCFPOpen: false
moreSpeakersToBeAnnounced: false

sponsors:
  cfs: false
  link_to_sponsorship: ""

tickets:
  url: https://www.eventora.com/en/Events/devit_conference_2018
  enabled: true
  early: true
  blind: false
  regular: false
