##
## The purpose of this configuration is to allow us to put
## toggles on things that change regulary in order to be
## switching them faster in the future
##

defaults:
  title: JUN 09-10, 2019, Thessaloniki
  # title: See you all next year!
  description: Find out the latest trends and techniques for Frontend, Backend, DevOps and Mobile! Meet all the cool people! We are 360Â° and proud of it!
  image: /assets/images/devit-og-general.jpg?1542468627

date: JUN 09-10, 2019
# date: See you all next year!
currentYear: "2019"

startDate: "2019-06-09"
endDate: "2019-06-10"

titlePostfix: " - DEVit Conference"

# Info about the venue
venue: blah blah

# Current mode. Site will be modified based on this
# values: "dday|nextday|nextblind|nextfull"
currentMode: "nextfull"

isCFPOpen: false
moreSpeakersToBeAnnounced: true
CFPlink: "https://goo.gl/forms/FqDnffxTnlgYVDej1"

sponsors:
  cfs: false
  link_to_sponsorship: ""

tickets:
  url: /tickets
  enabled: true
  early: true
  blind: false
  regular: false
